### ISSUE TITLE
code > dates & times

### ISSUE THREAD

**Issue by tiredandwired** [UMNLibraries/design-system#5]
is there a use case for until? 

should we change how we represent time in hours to mirror this recommendation?

midnight is lowercase here (my preference too!) but we currently have capitalized on our homepage, other places, etc. .. should make a note for lowercase midnight/noon if that’s how we’re representing it. 

perhaps a note should be included on how to use <time datetime=“”>

**Comment by puzumaki** [comment]
Noon and midnight here are presented in a sentence, hence the lowercasing. However, shifting date range to present as words rather than symbols could also imply lowercasing them (using sentence casing) as the second item as well. However, would we then have "noon to midnight", or would it be "Noon to midnight"?

**Comment by puzumaki** [comment]
Removing the suggestion for "until". Having an alternative seemed potentially useful for situations where the word "to" might be too much, e.g. "the two presentations to record go from noon until 2 p.m." vs. "the two presentations to record go from noon to 2 p.m." That's language for you though.

**Comment by puzumaki** [comment]
These were addressed. "Until" was removed, and following standard sentence casing, and with "noon" and "midnight" not being proper nouns, presenting them lowercase is accurate.
